Create dependency between openid clients and realm
By getting the realm id from `keycloak_realm.moc.id` instead of using a
static string, we establish a depdendency between the realm and the openid
clients such that opentofu will create the realm first.

Without this change, applying these resources to a fresh keycloak instance
will fail with:

    Error: error sending POST request to /admin/realms/moc/clients: 404 Not
    Found. Response body: {"error":"Realm not found."}

      with module.openshift_oidc["oac_prod_infra"].keycloak_openid_client.this,
      on modules/openshift-oidc/main.tf line 20, in resource "keycloak_openid_client" "this":
      20: resource "keycloak_openid_client" "this" {